### ISSUE TITLE
Error "data.substring is not a function"

### ISSUE THREAD

**Issue by tranchau1991** [ashi009/node-fast-html-parser#16]
> node_modules\node-html-parser\dist\index.js:576
                const text = data.substring(lastTextPos, kMarkupPattern.lastIndex - match[0].len
gth);
                                  ^
TypeError: data.substring is not a function
    at Object.parse (D:\xampp\htdocs\nodejs\parse\node_modules\node-html-parser\dist\index.js:57
6:35)
    at D:\xampp\htdocs\nodejs\parse\index.js:92:25
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

>

**Comment by Soumil07** [comment]
Likely what you are trying to parse is not a string object.

**Comment by tranchau1991** [comment]
that right. need use string for it (use .toString())
